/* Warning: Do not edit this file.
   Auto-generated by 'make_compiler_flags'.*/
const char* erts_build_flags_CFLAGS = "-O2";
const char* erts_build_flags_CONFIG_H = "N/A";
const char* erts_build_flags_LDFLAGS = "";
