/*
 * YCF stub implementations for utils.c
 * These are non-yielding stubs for functions that would normally be generated by YCF
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "sys.h"
#include "erl_vm.h"
#include "global.h"

/* Stub implementations for erts_qsort YCF functions */
void erts_qsort_ycf_gen_destroy(void* ycf_my_trap_state) {
    (void)ycf_my_trap_state;
}

void erts_qsort_ycf_gen_continue(long* ycf_number_of_reduction_param,
                                  void** ycf_trap_state,
                                  void* ycf_extra_context) {
    (void)ycf_number_of_reduction_param;
    (void)ycf_trap_state;
    (void)ycf_extra_context;
}

void erts_qsort_ycf_gen_yielding(long* ycf_nr_of_reductions_param,
                                 void** ycf_trap_state,
                                 void* ycf_extra_context,
                                 void* (*ycf_yield_alloc_fun)(size_t,void*),
                                 void (*ycf_yield_free_fun)(void*,void*),
                                 void* ycf_yield_alloc_free_context,
                                 size_t ycf_stack_alloc_size_or_max_size,
                                 void* ycf_stack_alloc_data,
                                 void *base,
                                 size_t nr_of_items,
                                 size_t item_size,
                                 erts_void_ptr_cmp_t compare) {
    (void)ycf_nr_of_reductions_param;
    (void)ycf_trap_state;
    (void)ycf_extra_context;
    (void)ycf_yield_alloc_fun;
    (void)ycf_yield_free_fun;
    (void)ycf_yield_alloc_free_context;
    (void)ycf_stack_alloc_size_or_max_size;
    (void)ycf_stack_alloc_data;
    /* Non-yielding version: just call standard qsort */
    qsort(base, nr_of_items, item_size, compare);
}
